github.com:
    users:
        WizdomDepot:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: WizdomDepot
